using System.Text.RegularExpressions;
using D365FO.Core.Eval;
using D365FO.Core.Knowledge;
using Xunit;

namespace D365FO.Core.Tests;

/// <summary>
/// The rule canon has one home. These tests are the guard on audit finding K1: the same X++
/// rules used to be written out in the agent system prompt, in the MCP surface and in the
/// skill files, so a correction landed in one and quietly missed the other two.
///
/// Two of the three consumers now compose their output from <see cref="RuleCanon"/> at
/// runtime, so drift there is unrepresentable. The third — the routers
/// <c>skills/d365fo-cli/SKILL.md</c>, <c>skills/anthropic/d365fo-cli/SKILL.md</c> and
/// <c>skills/copilot/d365fo-cli.instructions.md</c>, files on disk — is generated by <c>scripts/emit-skills.py</c>, and the last test here
/// fails locally for the same reason CI's drift job fails.
/// </summary>
public class RuleCanonTests
{
    private static readonly string RepoRoot =
        EvalPaths.FindRepoRoot() ?? throw new InvalidOperationException("Could not locate repo root for tests.");

    /// <summary>Canon ids at least one consumer depends on; losing one silently empties a rule section.</summary>
    private static readonly string[] RequiredIds =
        ["never-auto", "core", "queries", "coc", "aot-xml-safety", "classes", "statements", "bp"];

    [Fact]
    public void Every_required_canon_id_is_declared_exactly_once()
    {
        Assert.All(RequiredIds, id => Assert.NotNull(RuleCanon.Find(id)));

        // Load() throws on a duplicate id, so simply touching Blocks proves uniqueness;
        // assert it explicitly so the intent survives a refactor of Load().
        var ids = RuleCanon.Blocks.Select(b => b.Id).ToList();
        Assert.Equal(ids.Count, ids.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void Every_block_carries_content_and_names_its_topic()
    {
        Assert.All(RuleCanon.Blocks, b =>
        {
            Assert.False(string.IsNullOrWhiteSpace(b.Text), $"canon '{b.Id}' is empty");
            Assert.NotNull(KnowledgeBase.Get(b.TopicId));
        });
    }

    [Fact]
    public void Requiring_an_undeclared_id_fails_loudly()
    {
        // A consumer that asked for a renamed id would otherwise emit a system prompt with a
        // silently missing rule section — the exact failure mode this class exists to prevent.
        var ex = Assert.Throws<InvalidOperationException>(() => RuleCanon.Require("no-such-canon"));
        Assert.Contains("Declared ids:", ex.Message);
    }

    /// <summary>
    /// All three routers: the Copilot skill lists <c>references/&lt;id&gt;.md</c> by name, the Claude
    /// skill links each sibling topic skill, the legacy Copilot instructions link each sibling file.
    /// </summary>
    [Theory]
    [InlineData("skills/d365fo-cli/SKILL.md", "| `{0}` |")]
    [InlineData("skills/anthropic/d365fo-cli/SKILL.md", "| [`{0}`](../{0}/SKILL.md) |")]
    [InlineData("skills/copilot/d365fo-cli.instructions.md", "| [`{0}`]({0}.instructions.md) |")]
    public void Skill_md_carries_the_generated_canon_verbatim(string relativePath, string rowFormat)
    {
        var path = Path.Combine(RepoRoot, relativePath);
        var text = File.ReadAllText(path).Replace("\r\n", "\n");

        var canonRegion = Region(text, "canon");
        foreach (var id in new[] { "never-auto", "core", "coc", "aot-xml-safety", "bp" })
        {
            Assert.True(canonRegion.Contains(RuleCanon.Require(id), StringComparison.Ordinal),
                $"SKILL.md's canon region is missing (or has a stale copy of) '{id}' — " +
                "run `python scripts/emit-skills.py` and commit.");
        }

        // The reference table must list every topic; a topic added without re-emitting would
        // otherwise be invisible to the skill.
        var references = Region(text, "references");
        Assert.All(KnowledgeBase.Topics, t =>
            Assert.True(references.Contains(string.Format(rowFormat, t.Id), StringComparison.Ordinal),
                $"{relativePath}'s topic table does not list '{t.Id}' — run `python scripts/emit-skills.py`."));
    }

    [Fact]
    public void Mcp_server_instructions_carry_the_canon()
    {
        var instructions = D365FO.Mcp.ServerInstructions.Text;

        foreach (var id in new[] { "never-auto", "core", "queries", "coc", "aot-xml-safety", "bp" })
        {
            Assert.Contains(RuleCanon.Require(id), instructions, StringComparison.Ordinal);
        }

        // The narrative lead-in is what makes the rules actionable for a client that has not
        // called a tool yet; losing it would leave a wall of rules with no loop to apply them in.
        Assert.Contains("prepare → generate → validate", instructions, StringComparison.Ordinal);
    }

    private static string Region(string text, string name)
    {
        var m = Regex.Match(text, $"<!-- BEGIN {name} -->\n(.*?)<!-- END {name} -->", RegexOptions.Singleline);
        Assert.True(m.Success, $"SKILL.md has no '{name}' generated region");
        return m.Groups[1].Value;
    }
}
